### ISSUE TITLE
Creating Web Animations - Chapter 8 - Cooler Links Animations

### ISSUE THREAD

**Issue by quangv** [kirupa/kirupa#6]
Hey Kirupa,

I'm going through your book "Creating Web Animations" and am enjoying it, Thank you! I'm learning a lot.

I am having a little trouble with chapter 8, cooler links animation, here's my pen:

https://codepen.io/quangv/pen/ZmPOpx/

I notice that it wasn't in the github repo, does it still work?

Thanks,
Quang

**Comment by kirupa** [comment]
Hi Quang - it should work! Let me try it out tomorrow and get back to you.

**Comment by quangv** [comment]
🤦‍♂️ Ahh, Thanks Kirupa :)
