### ISSUE TITLE
Typo “forgot” should be “forget” in react for beginners.

### ISSUE THREAD

**Issue by SaulHarwin** [kirupa/kirupa#7]
## Location of typo: 
Article: react for beginners -> creating complex components -> Why Component Composability Rocks.

## Typo itself: 
“When we are heads-down in React, we often tend to **forgot** that what we are ultimately creating is just plain and boring HTML, CSS, and JavaScript. The generated HTML for our color palette card looks as follows:“.

## Solution
“forgot” in bold should be changed to forget.

**Comment by kirupa** [comment]
Hi @SaulHarwin - sorry for the delay in getting back to you! I fixed the typo :-)
